### ISSUE TITLE
Open Drawer Manual

### ISSUE THREAD

**Issue by mongy92** [Tinysymphony/react-native-drawer-menu#14]
can you Explain example of how to open drawer manual using button , 
i can't understand how to use the ref ?

this is my example , and i want to use Button to open drawer , Can you Help Plz ?
`            
<Drawer
              style={{flex:1}}
              drawerWidth={MENU_WIDTH}
              drawerContent={drawerContent}
              type={Drawer.types.Overlay}
              customStyles={customStyles}
              drawerPosition={Drawer.positions.Right}
              onDrawerOpen={() => {console.log('Drawer is opened');}}
              onDrawerClose={() => {console.log('Drawer is closed')}}
              easingFunc={Easing.ease}

            >
            <View style={{backgroundColor:'gold', flex:1, alignItems:'center' , 
            justifyContent:'center'}}>
            <View style={{
                    position:'absolute',
                    top:30,
                    right:20
                }}>
                <Button title="Click Here" color='black'/>

                </View>
                <Text style={{fontSize:30, color:'blue'}} >HOME PAGE</Text>
            </View>
            </Drawer>`

**Comment by BerkayGungor** [comment]
I dont know if its late or did you solve it but you can give your Drawer component a ref value like 
< Drawer ref='myDrawer' drawerWidth=.../> then you can access your Drawer with this.refs.myDrawer. And to open by clicking button just call it inside your Button tags like this {this.refs.myDrawer.openDrawer()} I hope this helps your question or other people that are looking for answer.
