### ISSUE TITLE
Is that possible to have 2 drawers with this project

### ISSUE THREAD

**Issue by ziofat** [Tinysymphony/react-native-drawer-menu#2]
I want to have 2 drawers from both left and right of the view. Is that possible?

**Comment by Tinysymphony** [comment]
@ziofat It's not supported now. It will have a refactor in next version. Thanks for using. ：）

**Comment by Tinysymphony** [comment]
@ziofat In version 0.2.0, You can use the `Drawer.position.Both` type to make this. 🎉

**Comment by ziofat** [comment]
That's awesome, thanks.
