### ISSUE TITLE
What is the missing required style?

### ISSUE THREAD

**Issue by cicobuff** [Tinysymphony/react-native-drawer-menu#6]
HI, thanks for the drawer.
But what is the styles you used in the readme?
`<View style={styles.leftTop}/>`
`<View style={styles.leftBottom}>`
You made references to them but I cant find it in the sources.

**Comment by Tinysymphony** [comment]
It's just an example style, you can define your own one. 

You can learn how to use this component from `index.ios.js`, which contains a complete example.

``` js
import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
 leftTop: {
    flex: 1,
    justifyContent: 'space-around',
    alignItems: 'stretch',
    alignSelf: 'stretch',
    backgroundColor: '#8ad8dd'
  },
  leftBottom: {
    flex: 2,
    justifyContent: 'space-around',
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: '#f0f0f0'
  }
});
```

**Comment by cicobuff** [comment]
Thanks!
