### ISSUE TITLE
Maximum drawer width

### ISSUE THREAD

**Issue by ptfly** [Tinysymphony/react-native-drawer-menu#7]
I see there is something odd: 
```this.MAX_DX = drawerWidth > 0.8 * width ? 0.8 * width : drawerWidth;```

I'd suggest removing this because may not fit some use cases where people may want 90% of the screen for example.

Although, good plugin, thanks for making it available to the public!

**Comment by Tinysymphony** [comment]
@ptfly Yes, I've thought about this problem. In order to have space to drug the drawer back, I limited the maximum width of the drawer to 80%. I will change it in later version and add a suggestion in README.md. 

Thanks for your issue!

**Comment by Tinysymphony** [comment]
@ptfly now `drawerWidth` can be any value you want in version 0.2.4   The maximum value is the width of screen.
