### ISSUE TITLE
Warning: BackAndroid is deprecated.

### ISSUE THREAD

**Issue by hyochan35** [Tinysymphony/react-native-drawer-menu#8]
Keeps showing warning in RN>=0.44 plz fix this issue.

**Comment by Tinysymphony** [comment]
@hyochan35 After updating RN to 0.44, I don't meet the same warning. I've checked recent issues and PRs of RN, find a issue and two PRs related to this problem. [issue1330](https://github.com/react-community/react-navigation/issues/1330)   [PR1333](https://github.com/react-community/react-navigation/pull/1333)   [PR1520](https://github.com/react-community/react-navigation/pull/1520) 

You can add this line in your project to prevent this warning temporarily:
`console.ignoredYellowBox = ['Warning: BackAndroid']`

**Comment by hyochan35** [comment]
Thanks for reply.
